### ISSUE TITLE
无法打开“MiniAppBuilder”，因为无法验证开发者。

### ISSUE THREAD

**Issue by jhxxs** [yujon/ipa-mac-builder#3]
执行了`xattr.sh`仍然无法运行后续命令

![image](https://github.com/yujon/ipa-mac-builder/assets/7448223/d2b4524c-fd85-4ead-bb2d-59242236869b)

系统：13.4 (22F66)

**Comment by yujon** [comment]
系统设备-》隐私与安全性，信任下该程序
